[toolchain]
channel = "1.75.0"
components = [
    "rustfmt",
    "clippy", 
    "rust-src",
    "rust-analyzer"
]
targets = [
    "x86_64-unknown-linux-gnu",
    "x86_64-pc-windows-msvc", 
    "x86_64-apple-darwin",
    "aarch64-apple-darwin"
]
profile = "default" 