name: Deploy Documentation

on:
  push:
    branches: [ main ]
    paths: 
      - 'docs/**'
      - '.github/workflows/docs.yml'
  pull_request:
    branches: [ main ]
    paths: 
      - 'docs/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write

    concurrency:
      group: "pages"
      cancel-in-progress: false

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Rust
      uses: dtolnay/rust-toolchain@stable

    - name: Install mdBook
      run: |
        cargo install mdbook
        cargo install mdbook-linkcheck
        cargo install mdbook-toc
        cargo install mdbook-mermaid

    - name: Setup Pages
      id: pages
      uses: actions/configure-pages@v3

    - name: Build documentation
      run: |
        cd docs
        mdbook build

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v2
      with:
        path: docs/book

    - name: Deploy to GitHub Pages
      id: deployment
      if: github.ref == 'refs/heads/main'
      uses: actions/deploy-pages@v2 